/**:
  ros__parameters:
    # These control how fast actions occur on the dog
    seconds_per_swing: 0.25
    standup_time: 1.5
    # These are Kp and Kd constants used for all motors
    stiffness: 90.0
    damping: 3.0
    # This is related to the force into the ground right before the step.
    # It's the distance into the floor it "pushes"
    delta: 0.01
    # How high the dog is off the floor in the standing position
    stand_percentage: 0.8
    # These are for constructing the step. 
    # X (forward/backwards) params:
    stroke_length_x: 0.05 # 0.05 is good for trot. 0.025 is about max for sideways
    dx1: 0.0125
    dx2: 0.0125
    # Z (left/right) params:
    stroke_length_z: 0.025 # 0.05 is good for trot. 0.025 is about max for sideways
    dz1: 0.0125
    dz2: 0.0125
    # Y (Up/down) params
    step_height: 0.04
    dy: 0.0125
    # gait type: 0 = single leg, 1 = tripod, 2 = trot
    gait_type: 2
    # Must be at least 1
    tripod_offset: 4
    # 0 for continuous trot, any larger number for pauses
    trot_offset: 0
    # Used to automatically stop walking after a certain amount of steps.
    step_limit: true
    nsteps: 16