/**:
  ros__parameters:
    seconds_per_swing: 0.25
    stroke_length: 0.1 # 0.2 is really zooming
    standup_time: 1.5
    stiffness: 90.0
    damping: 3.0
    delta: 0.025
    stand_percentage: 0.8
    step_height: 0.10
    gait_type: 2 # 0 = single leg, 1 = tripod, 2 = trot
    tripod_offset: 4
    trot_offset: 4
    step_limit: true
    nsteps: 5