/**:
  ros__parameters:
    seconds_per_swing: 0.5
    stroke_length: 0.1
    standup_time: 1.5
    stiffness: 95.0
    damping: 2.0
    delta: 0.025
    stand_percentage: 0.8
    gait_type: 0 # 0 = single leg, 1 = tripod, 2 = trot
